# Generated by Django 4.1.5 on 2024-10-27 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DropPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='drop_points')),
            ],
            options={
                'verbose_name': 'Drop Point',
                'verbose_name_plural': 'Drop Points',
            },
        ),
        migrations.CreateModel(
            name='RecycledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='recycled_items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.droppoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recycled Item',
                'verbose_name_plural': 'Recycled Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
